package exceptions;

public class throwsExample4 {

	public static void main(String[] args) {
		
		try {
			
			System.out.println("hello");
		} catch(ArithmeticException e ){
			
			
		}
		
	}

}
