package exceptions;

public class throwExample1 {
	
	//Main method is responsible to creating internally exception object and calling JMV 

	public static void main(String[] args) {
		
		System.out.println(10/0);

	}

}
